"""Modal dialog showing the citation block originally printed by the bash
scripts on completion. Each script has its own list of citations.

The user can opt out via "Don't show again" — a flag persisted in
:class:`Settings` and rechecked on every successful run.
"""
from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QCheckBox,
    QDialog,
    QDialogButtonBox,
    QLabel,
    QTextBrowser,
    QVBoxLayout,
    QWidget,
)

from jamdock_gui.settings import Settings


# ---- citation libraries (verbatim from the bash scripts) ---------------
JAMLIB_CITATIONS_HTML = """
<h3>Please cite the following:</h3>
<ul>
  <li><b>Method paper.</b> Barbosa Pereira, P.J., Ripoll-Rozada, J.,
      Macedo-Ribeiro, S., &amp; Manso, J.A. (2025).
      Protocol for an automated virtual screening pipeline including
      library generation and docking evaluation.
      <i>STAR Protocols</i> <b>6</b>(4), 104161.
      <a href="https://doi.org/10.1016/j.xpro.2025.104161">DOI</a></li>
  <li>Manso, J.A. (2025). <i>jamdock-suite</i>. Zenodo.
      <a href="https://doi.org/10.5281/zenodo.15577778">10.5281/zenodo.15577778</a></li>
  <li>O'Boyle, N.M. <i>et al.</i> (2011). Open Babel.
      <i>J. Cheminformatics</i> <b>3</b>, 33.
      <a href="https://doi.org/10.1186/1758-2946-3-33">DOI</a></li>
  <li>Irwin, J.J. <i>et al.</i> (2020). ZINC20.
      <i>J. Chem. Inf. Model.</i> <b>60</b>, 6065–6073.
      <a href="https://doi.org/10.1021/acs.jcim.0c00675">DOI</a></li>
  <li>Sterling, T. &amp; Irwin, J.J. (2015). ZINC 15.
      <i>J. Chem. Inf. Model.</i> <b>55</b>, 2324–2337.
      <a href="https://doi.org/10.1021/acs.jcim.5b00559">DOI</a></li>
  <li>Irwin, J.J. &amp; Shoichet, B.K. (2005). ZINC.
      <i>J. Chem. Inf. Model.</i> <b>45</b>, 177–182.
      <a href="https://doi.org/10.1021/ci049714+">DOI</a></li>
</ul>
<h4>Disclaimer</h4>
<p>This program is licensed under
<a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>.
It downloads compounds from the free ZINC database (zinc.docking.org), provided
by the Irwin and Shoichet Laboratories, and from files.docking.org and
files2.docking.org.</p>
<p><b>The libraries generated by this program are for personal, academic, and
non-commercial use only.</b> Redistribution to third parties is limited and must
fully comply with the original ZINC license terms.</p>
"""

JAMRECEPTOR_CITATIONS_HTML = """
<h3>Please cite the following:</h3>
<ul>
  <li><b>Method paper.</b> Barbosa Pereira, P.J., Ripoll-Rozada, J.,
      Macedo-Ribeiro, S., &amp; Manso, J.A. (2025).
      Protocol for an automated virtual screening pipeline including
      library generation and docking evaluation.
      <i>STAR Protocols</i> <b>6</b>(4), 104161.
      <a href="https://doi.org/10.1016/j.xpro.2025.104161">DOI</a></li>
  <li>Manso, J.A. (2025). <i>jamdock-suite</i>. Zenodo.
      <a href="https://doi.org/10.5281/zenodo.15577778">10.5281/zenodo.15577778</a></li>
  <li>Morris, G.M. <i>et al.</i> (2009). AutoDock4 and AutoDockTools4.
      <i>J. Comput. Chem.</i> <b>30</b>, 2785–2791.
      <a href="https://doi.org/10.1002/jcc.21256">DOI</a></li>
  <li>Le Guilloux, V. <i>et al.</i> (2009). Fpocket.
      <i>BMC Bioinformatics</i> <b>10</b>, 168.
      <a href="https://doi.org/10.1186/1471-2105-10-168">DOI</a></li>
</ul>
"""

JAMQVINA_CITATIONS_HTML = """
<h3>Please cite the following:</h3>
<ul>
  <li><b>Method paper.</b> Barbosa Pereira, P.J., Ripoll-Rozada, J.,
      Macedo-Ribeiro, S., &amp; Manso, J.A. (2025).
      Protocol for an automated virtual screening pipeline including
      library generation and docking evaluation.
      <i>STAR Protocols</i> <b>6</b>(4), 104161.
      <a href="https://doi.org/10.1016/j.xpro.2025.104161">DOI</a></li>
  <li>Manso, J.A. (2025). <i>jamdock-suite</i>. Zenodo.
      <a href="https://doi.org/10.5281/zenodo.15577778">10.5281/zenodo.15577778</a></li>
  <li>Trott, O. &amp; Olson, A.J. (2010). AutoDock Vina.
      <i>J. Comput. Chem.</i> <b>31</b>, 455–461.
      <a href="https://doi.org/10.1002/jcc.21334">DOI</a></li>
  <li>Alhossary, A. <i>et al.</i> (2015). QuickVina 2.
      <i>Bioinformatics</i> <b>31</b>, 2214–2216.
      <a href="https://doi.org/10.1093/bioinformatics/btv082">DOI</a></li>
</ul>
"""


class CitationDialog(QDialog):
    """Citations + optional disclaimer + 'Don't show again' opt-out."""

    def __init__(
        self,
        parent: QWidget | None = None,
        *,
        title: str = "Citations",
        body_html: str = JAMLIB_CITATIONS_HTML,
        settings: Settings | None = None,
    ) -> None:
        super().__init__(parent)
        self.setWindowTitle(title)
        self.setModal(True)
        self.resize(640, 520)
        self._settings = settings

        layout = QVBoxLayout(self)
        intro = QLabel(
            "<b>Thank you for using jamdock-gui.</b> "
            "If you publish results obtained with this tool, please cite:"
        )
        intro.setWordWrap(True)
        layout.addWidget(intro)

        body = QTextBrowser()
        body.setOpenExternalLinks(True)
        body.setHtml(body_html)
        layout.addWidget(body, 1)

        self._cb_dont_show = QCheckBox("Don't show citations again on success")
        layout.addWidget(self._cb_dont_show)

        buttons = QDialogButtonBox(QDialogButtonBox.Ok)
        buttons.accepted.connect(self.accept)
        layout.addWidget(buttons)

    # ------------------------------------------------------------------
    def accept(self) -> None:
        if self._cb_dont_show.isChecked() and self._settings is not None:
            self._settings.set_show_citations(False)
        super().accept()

    # ------------------------------------------------------------------
    @staticmethod
    def maybe_show(
        parent: QWidget | None,
        settings: Settings,
        *,
        title: str,
        body_html: str,
    ) -> None:
        """Show the dialog only if the user hasn't opted out."""
        if not settings.show_citations_on_complete():
            return
        dlg = CitationDialog(parent, title=title, body_html=body_html, settings=settings)
        dlg.exec()
